presubmits:
  hybridapp-io/ham-application-assembler:
  - name: check-ham-application-assembler
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/hybridapp-io/ham-application-assembler
    rerun_command: /test check-ham-application-assembler
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/multicloudlab/check-tool:v20200319-b5bfe54
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?check(?:.*?)?$'
  - name: test-ham-application-assembler-amd64
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/hybridapp-io/ham-application-assembler
    rerun_command: /test test-ham-application-assembler-amd64
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: test-ham-application-assembler-ppc64le
    cluster: ppc64le
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/hybridapp-io/ham-application-assembler
    rerun_command: /test test-ham-application-assembler-ppc64le
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: test-ham-application-assembler-s390x
    cluster: s390x
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/hybridapp-io/ham-application-assembler
    rerun_command: /test test-ham-application-assembler-s390x
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: build-ham-application-assembler-amd64
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/hybridapp-io/ham-application-assembler
    rerun_command: /test build-ham-application-assembler-amd64
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
  - name: build-ham-application-assembler-ppc64le
    cluster: ppc64le
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/hybridapp-io/ham-application-assembler
    rerun_command: /test build-ham-application-assembler-ppc64le
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
  - name: build-ham-application-assembler-s390x
    cluster: s390x
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/hybridapp-io/ham-application-assembler
    rerun_command: /test build-ham-application-assembler-s390x
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
postsubmits:
  hybridapp-io/ham-application-assembler:
  - name: coverage-ham-application-assembler-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/hybridapp-io/ham-application-assembler
    spec:
      containers:
      - command:
        - make
        - coverage
        image: quay.io/multicloudlab/check-tool:v20200319-b5bfe54
        name: ""
        env:
        - name: CODECOV_TOKEN
          valueFrom:
            secretKeyRef:
              name: hybridapp-io-ham-application-assembler-codecov-token
              key: codecov-token
        securityContext:
          privileged: true
  - name: build-ham-application-assembler-amd64-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/hybridapp-io/ham-application-assembler
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: build-ham-application-assembler-ppc64le-postsubmit
    cluster: ppc64le
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/hybridapp-io/ham-application-assembler
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: build-ham-application-assembler-s390x-postsubmit
    cluster: s390x
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/hybridapp-io/ham-application-assembler
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: image-ham-application-assembler-amd64-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/hybridapp-io/ham-application-assembler
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: image-ham-application-assembler-ppc64le-postsubmit
    cluster: ppc64le
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/hybridapp-io/ham-application-assembler
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: image-ham-application-assembler-s390x-postsubmit
    cluster: s390x
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/hybridapp-io/ham-application-assembler
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: multiarch-image-ham-application-assembler-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/hybridapp-io/ham-application-assembler
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - multiarch-image
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
