presubmits:
  IBM/ibm-monitoring-prometheus-operator-ext:
  - name: build_ibm-monitoring-prometheus-operator-ext
    branches:
    - ^master$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    rerun_command: /test build ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - make
        - build
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?: .*?)?$'
  - name: check_ibm-monitoring-prometheus-operator-ext
    branches:
    - ^master$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    rerun_command: /test check ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?check(?: .*?)?$'
  - name: test_ibm-monitoring-prometheus-operator-ext
    branches:
    - ^master$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    rerun_command: /test test ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - make
        - test
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?: .*?)?$'

postsubmits:
  IBM/ibm-monitoring-prometheus-operator-ext:
  - name: check_ibm-monitoring-prometheus-operator-ext_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
  - name: test_ibm-monitoring-prometheus-operator-ext_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - make
        - test
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
  - name: coverage_ibm-monitoring-prometheus-operator-ext_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - make
        - coverage
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        env:
        - name: CODECOV_TOKEN
          valueFrom:
            secretKeyRef:
              name: ibm-monitoring-prometheus-operator-ext-codecov-token
              key: codecov-token
        securityContext:
          privileged: true
  - name: build_ibm-monitoring-prometheus-operator-ext_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - make
        - build
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
  - name: images_ibm-monitoring-prometheus-operator-ext_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - images
        image: quay.io/multicloudlab/multicloudlab-builder:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
