presubmits:
  IBM/ibm-monitoring-prometheus-operator-ext:
  - name: build_ibm-monitoring-prometheus-operator-ext
    branches:
    - ^master$
    - ^release-cd$
    - ^release-eus$
    - ^release-efix$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    rerun_command: /test build ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/cicdtest/build-tool:v20231207-0e814149b
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?: .*?)?$'
  - name: check_ibm-monitoring-prometheus-operator-ext
    branches:
    - ^master$
    - ^release-cd$
    - ^release-eus$
    - ^release-efix$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    rerun_command: /test check ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/cicdtest/check-tool:v20231207-0e814149b
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?check(?: .*?)?$'
  - name: test_ibm-monitoring-prometheus-operator-ext
    branches:
    - ^master$
    - ^release-cd$
    - ^release-eus$
    - ^release-efix$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    rerun_command: /test test ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/cicdtest/build-tool:v20231207-0e814149b
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?: .*?)?$'

postsubmits:
  IBM/ibm-monitoring-prometheus-operator-ext:
  - name: check_ibm-monitoring-prometheus-operator-ext_postsubmit
    branches:
    - ^master$
    - ^release-cd$
    - ^release-eus$
    - ^release-efix$
    decorate: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/cicdtest/check-tool:v20231207-0e814149b
        name: ""
        securityContext:
          privileged: true
  - name: test_ibm-monitoring-prometheus-operator-ext_postsubmit
    branches:
    - ^master$
    - ^release-cd$
    - ^release-eus$
    - ^release-efix$
    decorate: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/cicdtest/build-tool:v20231207-0e814149b
        name: ""
        securityContext:
          privileged: true
  - name: build_ibm-monitoring-prometheus-operator-ext_postsubmit
    branches:
    - ^master$
    - ^release-cd$
    - ^release-eus$
    - ^release-efix$
    decorate: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/cicdtest/build-tool:v20231207-0e814149b
        name: ""
        securityContext:
          privileged: true
  - name: images_ibm-monitoring-prometheus-operator-ext_postsubmit
    branches:
    - ^master$
    - ^release-cd$
    - ^release-eus$
    - ^release-efix$
    decorate: true
    path_alias: github.com/IBM/ibm-monitoring-prometheus-operator-ext
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - images
        image: quay.io/cicdtest/build-tool:v20231207-0e814149b
        name: ""
        securityContext:
          privileged: true

