triggers:
- repos:
  - IBM
  - hybridapp-io
  - multicloudlab
  - rh-ibm-synergy

config_updater:
  maps:
    prow/s3/config.yaml:
      name: config
    prow/s3/plugins.yaml:
      name: plugins
    prow/cluster/jobs/**/*.yaml:
      name: job-config

plugins:
  IBM:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - golint
    - heart
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - milestone
    - owners-label
    - project
    - retitle
    - shrug
    - size
    - stage
    - trigger
    - verify-owners
    - welcome
    - wip
    - yuks
  IBM/test-infra:
    plugins:
    - config-updater

  hybridapp-io:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - golint
    - heart
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - milestone
    - owners-label
    - project
    - retitle
    - shrug
    - size
    - stage
    - trigger
    - verify-owners
    - welcome
    - wip
    - yuks

  multicloudlab:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - dog
    - golint
    - heart
    - help
    - hold
    - label
    - lgtm
    - lifecycle
    - milestone
    - milestonestatus
    - override
    - owners-label
    - pony
    - project
    - retitle
    - shrug
    - skip
    - size
    - stage
    - trigger
    - verify-owners
    - welcome
    - wip
    - yuks

  rh-ibm-synergy:
    plugins:
    - approve
    - assign
    - blunderbuss
    - golint
    - help
    - hold
    - lgtm
    - lifecycle
    - size
    - trigger
    - verify-owners
    - wip

external_plugins:
  IBM:
  # - name: needs-rebase
  #   events:
  #   - pull_request
  - name: cherrypicker
    events:
      - issue_comment
      - pull_request
  hybridapp-io:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
      - issue_comment
      - pull_request
  multicloudlab:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
      - issue_comment
      - pull_request
  # rh-ibm-synergy:
  # - name: needs-rebase
  #   events:
  #   - pull_request
  # - name: cherrypicker
  #   events:
  #     - issue_comment
  #     - pull_request
