apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cherrypicker
  labels:
    app: cherrypicker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cherrypicker
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: cherrypicker
        image: gcr.io/k8s-prow/cherrypicker:v20191011-80f304f54
        args:
        - --dry-run=false
        - --use-prow-assignments=false
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        ports:
        - name: http
          containerPort: 8888
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: oauth
        secret:
          secretName: oauth-token
---
apiVersion: v1
kind: Service
metadata:
  name: cherrypicker
  labels:
    app: cherrypicker
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: cherrypicker
  type: ClusterIP
---
