presubmits:
  IBM/ibm-ingress-nginx-operator:
  - name: build_ibm-ingress-nginx-operator
    branches:
    - ^master$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/ibm-ingress-nginx-operator
    rerun_command: /test build ibm-ingress-nginx-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?: .*?)?$'
  - name: check_ibm-ingress-nginx-operator
    branches:
    - ^master$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/ibm-ingress-nginx-operator
    rerun_command: /test check ibm-ingress-nginx-operator
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/multicloudlab/check-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?check(?: .*?)?$'
  - name: test_ibm-ingress-nginx-operator
    branches:
    - ^master$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/ibm-ingress-nginx-operator
    rerun_command: /test test ibm-ingress-nginx-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?: .*?)?$'

postsubmits:
  IBM/ibm-ingress-nginx-operator:
  - name: check_ibm-ingress-nginx-operator_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/ibm-ingress-nginx-operator
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/multicloudlab/check-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
  - name: test_ibm-ingress-nginx-operator_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/ibm-ingress-nginx-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
  - name: coverage_ibm-ingress-nginx-operator_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/ibm-ingress-nginx-operator
    spec:
      containers:
      - command:
        - make
        - coverage
        image: quay.io/multicloudlab/check-tool:v20200817-b1f2b4c05
        name: ""
        env:
        - name: CODECOV_TOKEN
          valueFrom:
            secretKeyRef:
              name: ibm-ingress-nginx-operator-codecov-token
              key: codecov-token
        securityContext:
          privileged: true
  - name: build_ibm-ingress-nginx-operator_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/ibm-ingress-nginx-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
  - name: images_ibm-ingress-nginx-operator_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/ibm-ingress-nginx-operator
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - images
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
