presubmits:
  IBM/operand-deployment-lifecycle-manager:
  - name: check-operand-deployment-lifecycle-manager
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    rerun_command: /test check-operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/multicloudlab/check-tool:v20201130-d61b998b6
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?check(?:.*?)?$'
  - name: test-operand-deployment-lifecycle-manager-amd64
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    rerun_command: /test test-operand-deployment-lifecycle-manager-amd64
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/multicloudlab/build-tool:v20210321-386f77ad4
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: kind-e2e-test-operand-deployment-lifecycle-manager-amd64
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    rerun_command: /test e2e-test-kind-operand-deployment-lifecycle-manager-amd64
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - e2e-test-kind
        image: quay.io/multicloudlab/build-tool:v20210203-ad22dc7f6
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?e2e-test-kind(?:.*?)?$'
postsubmits:
  IBM/operand-deployment-lifecycle-manager:
  - name: coverage-operand-deployment-lifecycle-manager-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - coverage
        image: quay.io/multicloudlab/build-tool:v20210321-386f77ad4
        name: ""
        env:
        - name: CODECOV_TOKEN
          valueFrom:
            secretKeyRef:
              name: operand-deployment-lifecycle-manager-codecov-token
              key: codecov-token
        securityContext:
          privileged: true
  - name: image-operand-deployment-lifecycle-manager-amd64-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20210321-386f77ad4
        name: ""
        securityContext:
          privileged: true
  - name: image-operand-deployment-lifecycle-manager-ppc64le-postsubmit
    cluster: ppc64le
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20210321-386f77ad4
        name: ""
        securityContext:
          privileged: true
  - name: image-operand-deployment-lifecycle-manager-s390x-postsubmit
    cluster: s390x
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20210321-386f77ad4
        name: ""
        securityContext:
          privileged: true
  - name: multiarch-image-operand-deployment-lifecycle-manager-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - multiarch-image
        image: quay.io/multicloudlab/build-tool:v20210321-386f77ad4
        name: ""
        securityContext:
          privileged: true
