presubmits:
  IBM/operand-deployment-lifecycle-manager:
  - name: build_operand-deployment-lifecycle-manager
    branches:
    - ^master$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    rerun_command: /test build operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - make
        - build
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?: .*?)?$'
  - name: check_operand-deployment-lifecycle-manager
    branches:
    - ^master$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    rerun_command: /test check operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?check(?: .*?)?$'
  - name: test_operand-deployment-lifecycle-manager
    branches:
    - ^master$
    decorate: true
    always_run: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    rerun_command: /test test operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - make
        - test
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?: .*?)?$'

postsubmits:
  IBM/operand-deployment-lifecycle-manager:
  - name: check_operand-deployment-lifecycle-manager_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
  - name: test_operand-deployment-lifecycle-manager_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - make
        - test
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
  - name: coverage_operand-deployment-lifecycle-manager_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - make
        - coverage
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        env:
        - name: CODECOV_TOKEN
          valueFrom:
            secretKeyRef:
              name: operand-deployment-lifecycle-manager-codecov-token
              key: codecov-token
        securityContext:
          privileged: true
  - name: build_operand-deployment-lifecycle-manager_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    spec:
      containers:
      - command:
        - make
        - build
        image: quay.io/multicloudlab/build-tools:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
  - name: images_operand-deployment-lifecycle-manager_postsubmit
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/operand-deployment-lifecycle-manager
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - images
        image: quay.io/multicloudlab/multicloudlab-builder:v20191217-d33a10d
        name: ""
        securityContext:
          privileged: true
