presubmits:
  IBM/ibm-management-ingress-operator:
  - name: check-ibm-management-ingress-operator
    cluster: default
    always_run: true
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/ibm-management-ingress-operator
    rerun_command: /test check-ibm-management-ingress-operator
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/cicdtest/check-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?check(?:.*?)?$'
  - name: test-ibm-management-ingress-operator
    cluster: default
    always_run: true
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/ibm-management-ingress-operator
    rerun_command: /test test-ibm-management-ingress-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: test-ibm-management-ingress-operator-ppc64le
    cluster: ppc64le
    always_run: true
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/ibm-management-ingress-operator
    rerun_command: /test test-ibm-management-ingress-operator-ppc64le
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: test-ibm-management-ingress-operator-s390x
    cluster: s390x
    always_run: true
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/ibm-management-ingress-operator
    rerun_command: /test test-ibm-management-ingress-operator-s390x
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: build-ibm-management-ingress-operator
    cluster: default
    always_run: true
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/ibm-management-ingress-operator
    rerun_command: /test build-ibm-management-ingress-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
  - name: build-ibm-management-ingress-operator-ppc64le
    cluster: ppc64le
    always_run: true
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/ibm-management-ingress-operator
    rerun_command: /test build-ibm-management-ingress-operator-ppc64le
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
  - name: build-ibm-management-ingress-operator-s390x
    cluster: s390x
    always_run: true
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/ibm-management-ingress-operator
    rerun_command: /test build-ibm-management-ingress-operator-s390x
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
postsubmits:
  IBM/ibm-management-ingress-operator:
  - name: build-ibm-management-ingress-operator-postsubmit
    cluster: default
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/ibm-management-ingress-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
  - name: build-ibm-management-ingress-operator-ppc64le-postsubmit
    cluster: ppc64le
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/ibm-management-ingress-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
  - name: build-ibm-management-ingress-operator-s390x-postsubmit
    cluster: s390x
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    path_alias: github.com/IBM/ibm-management-ingress-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
  - name: image-ibm-management-ingress-operator-postsubmit
    cluster: default
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/ibm-management-ingress-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
  - name: image-ibm-management-ingress-operator-ppc64le-postsubmit
    cluster: ppc64le
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/ibm-management-ingress-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
  - name: image-ibm-management-ingress-operator-s390x-postsubmit
    cluster: s390x
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/ibm-management-ingress-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true
  - name: multiarch-image-ibm-management-ingress-operator-postsubmit
    cluster: default
    branches:
    - ^master$
    - ^release-future$
    - ^release-efix$
    - ^release-eus$
    - ^release-k$
    - ^release-ltsr$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/ibm-management-ingress-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - multiarch-image
        image: quay.io/cicdtest/build-tool:v20231010-ce7835db7
        name: ""
        securityContext:
          privileged: true

