presubmits:
  IBM/prometheus-metrics-server-simulator:
  - name: check-prometheus-metrics-server-simulator
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    rerun_command: /test check-prometheus-metrics-server-simulator
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/multicloudlab/check-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?check(?:.*?)?$'
  - name: test-prometheus-metrics-server-simulator-amd64
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    rerun_command: /test test-prometheus-metrics-server-simulator-amd64
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: test-prometheus-metrics-server-simulator-ppc64le
    cluster: ppc64le
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    rerun_command: /test test-prometheus-metrics-server-simulator-ppc64le
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: test-prometheus-metrics-server-simulator-s390x
    cluster: s390x
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    rerun_command: /test test-prometheus-metrics-server-simulator-s390x
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: build-prometheus-metrics-server-simulator-amd64
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    rerun_command: /test build-prometheus-metrics-server-simulator-amd64
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
  - name: build-prometheus-metrics-server-simulator-ppc64le
    cluster: ppc64le
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    rerun_command: /test build-prometheus-metrics-server-simulator-ppc64le
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
  - name: build-prometheus-metrics-server-simulator-s390x
    cluster: s390x
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    rerun_command: /test build-prometheus-metrics-server-simulator-s390x
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
postsubmits:
  IBM/prometheus-metrics-server-simulator:
  - name: coverage-prometheus-metrics-server-simulator-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    spec:
      containers:
      - command:
        - make
        - coverage
        image: quay.io/multicloudlab/check-tool:v20200817-b1f2b4c05
        name: ""
        env:
        - name: CODECOV_TOKEN
          valueFrom:
            secretKeyRef:
              name: ibm-prometheus-metrics-server-simulator-codecov-token
              key: codecov-token
        securityContext:
          privileged: true
  - name: build-prometheus-metrics-server-simulator-amd64-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
  - name: build-prometheus-metrics-server-simulator-ppc64le-postsubmit
    cluster: ppc64le
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
  - name: build-prometheus-metrics-server-simulator-s390x-postsubmit
    cluster: s390x
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
  - name: image-prometheus-metrics-server-simulator-amd64-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
  - name: image-prometheus-metrics-server-simulator-ppc64le-postsubmit
    cluster: ppc64le
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
  - name: image-prometheus-metrics-server-simulator-s390x-postsubmit
    cluster: s390x
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
  - name: multiarch-image-prometheus-metrics-server-simulator-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/prometheus-metrics-server-simulator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - multiarch-image
        image: quay.io/multicloudlab/build-tool:v20200817-b1f2b4c05
        name: ""
        securityContext:
          privileged: true
