presubmits:
  IBM/hybridapplication-operator:
  - name: check-hybridapplication-operator
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/hybridapplication-operator
    rerun_command: /test check-hybridapplication-operator
    spec:
      containers:
      - command:
        - make
        - check
        image: quay.io/multicloudlab/check-tool:v20200319-b5bfe54
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?check(?:.*?)?$'
  - name: test-hybridapplication-operator-amd64
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/hybridapplication-operator
    rerun_command: /test test-hybridapplication-operator-amd64
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - test
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?test(?:.*?)?$'
  - name: build-hybridapplication-operator-amd64
    cluster: default
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/hybridapplication-operator
    rerun_command: /test build-hybridapplication-operator-amd64
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
  - name: build-hybridapplication-operator-ppc64le
    cluster: ppc64le
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/hybridapplication-operator
    rerun_command: /test build-hybridapplication-operator-ppc64le
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
  - name: build-hybridapplication-operator-s390x
    cluster: s390x
    always_run: true
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/hybridapplication-operator
    rerun_command: /test build-hybridapplication-operator-s390x
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
    trigger: '(?m)^/test (?:.*? )?build(?:.*?)?$'
postsubmits:
  IBM/hybridapplication-operator:
  - name: coverage-hybridapplication-operator-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/hybridapplication-operator
    spec:
      containers:
      - command:
        - make
        - coverage
        image: quay.io/multicloudlab/check-tool:v20200319-b5bfe54
        name: ""
        env:
        - name: CODECOV_TOKEN
          valueFrom:
            secretKeyRef:
              name: ibm-hybridapplication-operator-codecov-token
              key: codecov-token
        securityContext:
          privileged: true
  - name: build-hybridapplication-operator-amd64-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/hybridapplication-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: build-hybridapplication-operator-ppc64le-postsubmit
    cluster: ppc64le
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/hybridapplication-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: build-hybridapplication-operator-s390x-postsubmit
    cluster: s390x
    branches:
    - ^master$
    decorate: true
    path_alias: github.com/IBM/hybridapplication-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: image-hybridapplication-operator-amd64-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/hybridapplication-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: image-hybridapplication-operator-ppc64le-postsubmit
    cluster: ppc64le
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/hybridapplication-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: image-hybridapplication-operator-s390x-postsubmit
    cluster: s390x
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/hybridapplication-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - build-push-image
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
  - name: multiarch-image-hybridapplication-operator-postsubmit
    cluster: default
    branches:
    - ^master$
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: github.com/IBM/hybridapplication-operator
    spec:
      containers:
      - command:
        - entrypoint
        - make
        - multiarch-image
        image: quay.io/multicloudlab/build-tool:v20200320-5e25536
        name: ""
        securityContext:
          privileged: true
