plank:
  default_decoration_config:
    utility_images: # using the tag we identified above
      clonerefs: "quay.io/multicloudlab/k8s-prow-clonerefs:v20190917-395658c48"
      initupload: "quay.io/multicloudlab/k8s-prow-initupload:v20190917-395658c48"
      entrypoint: "quay.io/multicloudlab/k8s-prow-entrypoint:v20190917-395658c48"
      sidecar: "quay.io/multicloudlab/k8s-prow-sidecar:v20190917-395658c48"
    gcs_configuration:
      bucket: prow_job_bucket # the bucket we just made
      path_strategy: explicit
    gcs_credentials_secret: gcs-credentials # the secret we just made

prowjob_namespace: default
pod_namespace: test-pods

tide:
  merge_method:
    multicloudlab/oasis: squash
    multicloudlab/mygit: squash
    multicloudlab/test-infra: squash
    multicloudlab/tools: squash
    rh-ibm-synergy/multicloud-operators-foundation: squash
    IBM/go-repo-template: squash
    IBM/test-infra: squash
    IBM/healthcheck-service-operator: squash
    IBM/ibm-auditlogging-operator: squash
    IBM/ibm-catalog-operator: squash
    IBM/ibm-cert-manager-operator: squash
    IBM/ibm-cloudctl-operator: squash
    IBM/ibm-commonui-operator: squash
    IBM/ibm-helm-api-operator: squash
    IBM/ibm-helm-repo-operator: squash
    IBM/ibm-iam-operator: squash
    IBM/ibm-licensing-operator: squash
    IBM/ibm-management-repo-operator: squash
    IBM/ibm-metering-operator: squash
    IBM/ibm-mongodb-operator: squash
    IBM/ibm-mt-grqenforcer-operator: squash
    IBM/management-ingress-operator: squash
    IBM/meta-operator: squash
    IBM/ingress-nginx-operator: squash
    IBM/multicloud-operators-subscription-release: squash
    IBM/multicloud-operators-policy-controller: squash
    IBM/multicloud-operators-placementrule: squash
    IBM/multicloud-operators-deployable: squash
    IBM/multicloud-operators-channel: squash
    IBM/multicloud-operators-subscription: squash
    IBM/multicloud-multi-tenancy: squash
    IBM/multicloud-application-monitoring-dashboard: squash

  target_url: http://prow.purple-chesterfield.com/tide
  queries:
  - repos:
    - multicloudlab/oasis
    - multicloudlab/mygit
    - multicloudlab/test-infra
    - multicloudlab/tools
    - rh-ibm-synergy/multicloud-operators-foundation
    - IBM/go-repo-template
    - IBM/test-infra
    - IBM/healthcheck-service-operator
    - IBM/ibm-auditlogging-operator
    - IBM/ibm-catalog-operator
    - IBM/ibm-cert-manager-operator
    - IBM/ibm-cloudctl-operator
    - IBM/ibm-commonui-operator
    - IBM/ibm-helm-api-operator
    - IBM/ibm-helm-repo-operator
    - IBM/ibm-iam-operator
    - IBM/ibm-licensing-operator
    - IBM/ibm-management-repo-operator
    - IBM/ibm-metering-operator
    - IBM/ibm-mongodb-operator
    - IBM/ibm-mt-grqenforcer-operator
    - IBM/meta-operator
    - IBM/management-ingress-operator
    - IBM/ingress-nginx-operator
    - IBM/multicloud-operators-subscription-release
    - IBM/multicloud-operators-policy-controller
    - IBM/multicloud-operators-placementrule
    - IBM/multicloud-operators-deployable
    - IBM/multicloud-operators-channel
    - IBM/multicloud-operators-subscription
    - IBM/multicloud-multi-tenancy
    - IBM/multicloud-application-monitoring-dashboard
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - do-not-merge/invalid-owners-file
    - needs-rebase

  context_options:
    # Use branch protection options to define required and optional contexts
    from-branch-protection: true
    # Treat unknown contexts as optional
    skip-unknown-contexts: true

# branch-protection:
#   orgs:
#     IBM:
#       repos:
#         go-repo-template:
#           protect: true
#           # TODO: add ibm cla
#           # required_status_checks:
#           #   contexts:
#           #   - cla/ibm
#           exclude:
#             - "^revert-" # don't protect revert branches
#             - "^dependabot/" # don't protect branches created by dependabot
#             - "^greenkeeper/" # don't protect branches created by greenkeeper
#           required_status_checks:
#             contexts:
#             - continuous-integration/travis-ci/pr

presets:
# presets for private repos
- labels:
    preset-service-account: "true"
  env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/service-account/service-account.json
  - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
    value: /etc/service-account/service-account.json
  volumeMounts:
  - name: service
    mountPath: /etc/service-account
    readOnly: true
  volumes:
  - name: service
    secret:
      secretName: service-account
# presets for private repos
- labels:
    preset-private-repo: "true"
  env:
  - name: GOPRIVATE
    value: github.ibm.com,github.com/rh-ibm-synergy
  volumeMounts:
  - mountPath: /home/ssh
    name: ssh-keys-ssh-secret
    readOnly: true

# Enable GOPROXY by default
- env:
  - name: GOPROXY
    value: "https://proxy.golang.org"
  - name: BUILD_LOCALLY
    value: "0"
  - name: KUBEBUILDER_CONTROLPLANE_START_TIMEOUT
    value: "100s"
